spring:
  application:
    name: RealChatApp

  datasource:
    url: jdbc:postgresql://localhost:5432/realchatdb
    username: david
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      static-locations: classpath:/static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      indent-output: true
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.drtx.example: DEBUG

